name: slider_button
description: Customizable slider button widget for activating/deactivating some event.
version: 2.0.0
homepage: https://github.com/anirudhsharma392/Slider-Button

environment:
  sdk: "3.1.0"

dependencies:
  vibration: ^1.7.4-nullsafety
  shimmer: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

